version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=mydatabase
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
    depends_on:
      - mysql
    volumes:
      - ./laravel:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - laravel

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  random-http:
    image: mendhak/http-https-echo
    ports:
      - "8080:80"
    networks:
      - app-network
    profiles:
      random:
        - "thiio"

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
